trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'src/Identity/*'
    - 'devops/azure-devops/templates/*'

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: /devops/azure-devops/templates/build-dotnet-core.yaml
  parameters:
    buildConfiguration: 'Release'
    projectName: 'Identity'