trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'src/Api/*'

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: /devops/azure-devops/templates/build-dotnet-core.yaml
  parameters:
    buildConfiguration: 'Release'
    projectName: 'Api'